// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA9T0b1s8hq1-tRwKK6W3okdw1raPFDXE',
    appId: '1:415294544371:web:feb10a5daab85f1f34da86',
    messagingSenderId: '415294544371',
    projectId: 'goalkeeper-db759',
    authDomain: 'goalkeeper-db759.firebaseapp.com',
    storageBucket: 'goalkeeper-db759.firebasestorage.app',
    measurementId: 'G-69EMJ9M4GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKzhWMQUa7lOIOzsPhrb5n2xpR6p3_4rg',
    appId: '1:415294544371:android:6061bf2a60b0956334da86',
    messagingSenderId: '415294544371',
    projectId: 'goalkeeper-db759',
    storageBucket: 'goalkeeper-db759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKYNjG_ZZRGjMn-lb5tDTQ-KdP-nfNgbE',
    appId: '1:415294544371:ios:b091b4207e6daaa634da86',
    messagingSenderId: '415294544371',
    projectId: 'goalkeeper-db759',
    storageBucket: 'goalkeeper-db759.firebasestorage.app',
    iosBundleId: 'com.example.goalkeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKYNjG_ZZRGjMn-lb5tDTQ-KdP-nfNgbE',
    appId: '1:415294544371:ios:b091b4207e6daaa634da86',
    messagingSenderId: '415294544371',
    projectId: 'goalkeeper-db759',
    storageBucket: 'goalkeeper-db759.firebasestorage.app',
    iosBundleId: 'com.example.goalkeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA9T0b1s8hq1-tRwKK6W3okdw1raPFDXE',
    appId: '1:415294544371:web:b5bd734807e63eb734da86',
    messagingSenderId: '415294544371',
    projectId: 'goalkeeper-db759',
    authDomain: 'goalkeeper-db759.firebaseapp.com',
    storageBucket: 'goalkeeper-db759.firebasestorage.app',
    measurementId: 'G-4SX3REZELQ',
  );
}
